/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { SnapsRegistryController } from './SnapsRegistryController';

/**
 * Triggers an update of the registry database.
 *
 * If an existing update is in progress this function will await that update.
 */
export type SnapsRegistryControllerUpdateRegistryAction = {
  type: `SnapsRegistryController:updateRegistry`;
  handler: SnapsRegistryController['updateRegistry'];
};

export type SnapsRegistryControllerGetSnapAction = {
  type: `SnapsRegistryController:getSnap`;
  handler: SnapsRegistryController['getSnap'];
};

/**
 * Find an allowlisted version within a specified version range. Otherwise return the version range itself.
 *
 * @param snapId - The ID of the snap we are trying to resolve a version for.
 * @param versionRange - The version range.
 * @param refetch - An optional flag used to determine if we are refetching the registry.
 * @returns An allowlisted version within the specified version range if available otherwise returns the input version range.
 */
export type SnapsRegistryControllerResolveSnapVersionAction = {
  type: `SnapsRegistryController:resolveSnapVersion`;
  handler: SnapsRegistryController['resolveSnapVersion'];
};

/**
 * Get metadata for the given snap ID, if available, without updating registry.
 *
 * @param snapId - The ID of the snap to get metadata for.
 * @returns The metadata for the given snap ID, or `null` if the snap is not
 * verified.
 */
export type SnapsRegistryControllerGetSnapMetadataAction = {
  type: `SnapsRegistryController:getSnapMetadata`;
  handler: SnapsRegistryController['getSnapMetadata'];
};

/**
 * Union of all SnapsRegistryController action types.
 */
export type SnapsRegistryControllerMethodActions =
  | SnapsRegistryControllerUpdateRegistryAction
  | SnapsRegistryControllerGetSnapAction
  | SnapsRegistryControllerResolveSnapVersionAction
  | SnapsRegistryControllerGetSnapMetadataAction;
