# Allowlist for Git repositories that can be used as dependencies. We set it to
# an empty array to disallow all Git dependencies, as we don't use any and they
# can be a security risk.
approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

# Configure the NPM minimal age gate to 3 days, meaning packages must be at
# least 3 days old to be installed.
npmMinimalAgeGate: 4320 # 3 days (in minutes)

# Override the minimal age gate, allowing certain packages to be installed
# regardless of their publish age.
npmPreapprovedPackages:
  - '@metamask/*'
  - '@metamask-previews/*'
  - '@lavamoat/*'
  - lavamoat
  - lavamoat-core
  - lavamoat-tofu

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: 'https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js'
  - path: .yarn/plugins/local/plugin-workspaces-filter.js
  - path: .yarn/plugins/local/plugin-lifecycle-scripts.js

yarnPath: .yarn/releases/yarn-4.14.1.cjs
