enableScripts: false

enableTelemetry: 0

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: 'https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'
  - path: .yarn/plugins/local/plugin-workspaces-filter.js

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  '@graphql-tools/graphql-tag-pluck@*':
    dependencies:
      '@babel/core': 'patch:@babel/core@npm%3A7.21.0#./.yarn/patches/@babel-core-npm-7.21.0-fb3817b0e5.patch::locator=root%40workspace%3A.'
  '@parcel/types@*':
    dependencies:
      '@parcel/core': '2.8.3'
  '@wdio/browser-runner@*':
    dependencies:
      '@babel/core': 'patch:@babel/core@npm%3A7.21.0#./.yarn/patches/@babel-core-npm-7.21.0-fb3817b0e5.patch::locator=root%40workspace%3A'
  'gatsby@*':
    dependencies:
      babel-eslint: 10.1.0
