import chokidar from 'chokidar';
import { YargsArgs } from '../../types/yargs';
import { bundle } from '../build/bundle';
import {
  logError,
  getOutfilePath,
  validateDirPath,
  validateFilePath,
  validateOutfileName,
} from '../../utils';
import { snapEval } from '../eval/evalHandler';
import { manifestHandler } from '../manifest/manifestHandler';
import { processEval, processManifestCheck } from './utils';


/**
 * Watch a directory and its subdirectories for changes, and build when files
 * are added or changed.
 *
 * Ignores 'node_modules' and dotfiles.
 * Creates destination directory if it doesn't exist.
 *
 * @param argv - arguments as an object generated by yargs
 * @param argv.src - The source file path
 * @param argv.dist - The output directory path
 * @param argv.'outfileName' - The output file name
 */
export async function watch(argv: YargsArgs): Promise<void> {
  const { src, dist, outfileName } = argv;
  if (outfileName) {
    validateOutfileName(outfileName as string);
  }
  await validateFilePath(src);
  await validateDirPath(dist, true);
  const rootDir =
    src.indexOf('/') === -1 ? '.' : src.substring(0, src.lastIndexOf('/') + 1);
  const outfilePath = getOutfilePath(dist, outfileName as string);

  const watcher = chokidar.watch(rootDir, {
    ignoreInitial: true,
    ignored: [
      '**/node_modules/**',
      `**/${dist}/**`,
      `**/test/**`,
      `**/tests/**`,
      `**/*.test.js`,
      `**/*.test.ts`,
      /* istanbul ignore next */
      (str: string) => str !== '.' && str.startsWith('.'),
    ],
  });
  watcher
    .on('ready', async () => {
      await bundle(src, outfilePath, argv);
      processEval({ ...argv, bundle: outfilePath });
      processManifestCheck(argv);
    })
    .on('add', async (path: string) => {
      console.log(`File added: ${path}`);
      await bundle(src, outfilePath, argv);
      processEval({ ...argv, bundle: outfilePath });
      processManifestCheck(argv);
    })
    .on('change', async (path: string) => {
      console.log(`File changed: ${path}`);
      await bundle(src, outfilePath, argv);
      processEval({ ...argv, bundle: outfilePath });
      processManifestCheck(argv);
    })
    .on('unlink', (path: string) => console.log(`File removed: ${path}`))
    .on('error', (err: Error) => {
      logError(`Watcher error: ${err.message}`, err);
    });

  watcher.add(`${rootDir}`);
  console.log(`Watching '${rootDir}' for changes...`);
}
