/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { MultichainRouter } from './MultichainRouter';

/**
 * Handle an incoming JSON-RPC request tied to a specific scope by routing
 * to either a protocol Snap or an account Snap.
 *
 * Note: Addresses are considered case-sensitive by the MultichainRouter as
 * not all non-EVM chains are case-insensitive.
 *
 * @param options - An options bag.
 * @param options.connectedAddresses - Addresses currently connected to the
 * origin for the requested scope.
 * @param options.origin - The origin of the RPC request.
 * @param options.request - The JSON-RPC request.
 * @param options.scope - The CAIP-2 scope for the request.
 * @returns The response from the chosen Snap.
 * @throws If no handler was found.
 */
export type MultichainRouterHandleRequestAction = {
  type: `MultichainRouter:handleRequest`;
  handler: MultichainRouter['handleRequest'];
};

/**
 * Get a list of supported methods for a given scope.
 * This combines both protocol and account Snaps supported methods.
 *
 * @param scope - The CAIP-2 scope.
 * @returns A list of supported methods.
 */
export type MultichainRouterGetSupportedMethodsAction = {
  type: `MultichainRouter:getSupportedMethods`;
  handler: MultichainRouter['getSupportedMethods'];
};

/**
 * Get a list of supported accounts for a given scope.
 *
 * @param scope - The CAIP-2 scope.
 * @returns A list of CAIP-10 addresses.
 */
export type MultichainRouterGetSupportedAccountsAction = {
  type: `MultichainRouter:getSupportedAccounts`;
  handler: MultichainRouter['getSupportedAccounts'];
};

/**
 * Determine whether a given CAIP-2 scope is supported by the router.
 *
 * @param scope - The CAIP-2 scope.
 * @returns True if the router can service the scope, otherwise false.
 */
export type MultichainRouterIsSupportedScopeAction = {
  type: `MultichainRouter:isSupportedScope`;
  handler: MultichainRouter['isSupportedScope'];
};

/**
 * Union of all MultichainRouter action types.
 */
export type MultichainRouterMethodActions =
  | MultichainRouterHandleRequestAction
  | MultichainRouterGetSupportedMethodsAction
  | MultichainRouterGetSupportedAccountsAction
  | MultichainRouterIsSupportedScopeAction;
