/**
 * This file is auto generated by `@metamask/messenger/generate-action-types`.
 * Do not edit manually.
 */

import type { SnapInterfaceController } from './SnapInterfaceController';

/**
 * Create an interface in the controller state with the associated data.
 *
 * @param snapId - The snap id that created the interface.
 * @param content - The interface content.
 * @param context - An optional interface context object.
 * @param contentType - The type of content.
 * @returns The newly interface id.
 */
export type SnapInterfaceControllerCreateInterfaceAction = {
  type: `SnapInterfaceController:createInterface`;
  handler: SnapInterfaceController['createInterface'];
};

/**
 * Get the data of a given interface id.
 *
 * @param snapId - The snap id requesting the interface data.
 * @param id - The interface id.
 * @returns The interface state.
 */
export type SnapInterfaceControllerGetInterfaceAction = {
  type: `SnapInterfaceController:getInterface`;
  handler: SnapInterfaceController['getInterface'];
};

/**
 * Get the state of a given interface ID, if the interface has been displayed
 * at least once.
 *
 * @param snapId - The snap ID requesting the interface state.
 * @param id - The interface ID.
 * @returns The interface state.
 */
export type SnapInterfaceControllerGetInterfaceStateAction = {
  type: `SnapInterfaceController:getInterfaceState`;
  handler: SnapInterfaceController['getInterfaceState'];
};

/**
 * Update the interface with the given content.
 *
 * @param snapId - The snap id requesting the update.
 * @param id - The interface id.
 * @param content - The new content.
 * @param context - An optional interface context object.
 */
export type SnapInterfaceControllerUpdateInterfaceAction = {
  type: `SnapInterfaceController:updateInterface`;
  handler: SnapInterfaceController['updateInterface'];
};

/**
 * Delete an interface from state.
 *
 * @param id - The interface id.
 */
export type SnapInterfaceControllerDeleteInterfaceAction = {
  type: `SnapInterfaceController:deleteInterface`;
  handler: SnapInterfaceController['deleteInterface'];
};

/**
 * Update the interface state.
 *
 * @param id - The interface id.
 * @param state - The new state.
 */
export type SnapInterfaceControllerUpdateInterfaceStateAction = {
  type: `SnapInterfaceController:updateInterfaceState`;
  handler: SnapInterfaceController['updateInterfaceState'];
};

/**
 * Resolve the promise of a given interface approval request.
 * The approval needs to have the same ID as the interface.
 *
 * @param snapId - The snap id.
 * @param id - The interface id.
 * @param value - The value to resolve the promise with.
 */
export type SnapInterfaceControllerResolveInterfaceAction = {
  type: `SnapInterfaceController:resolveInterface`;
  handler: SnapInterfaceController['resolveInterface'];
};

/**
 * Set the interface as displayed.
 *
 * @param snapId - The snap ID requesting the update.
 * @param id - The interface ID.
 */
export type SnapInterfaceControllerSetInterfaceDisplayedAction = {
  type: `SnapInterfaceController:setInterfaceDisplayed`;
  handler: SnapInterfaceController['setInterfaceDisplayed'];
};

/**
 * Union of all SnapInterfaceController action types.
 */
export type SnapInterfaceControllerMethodActions =
  | SnapInterfaceControllerCreateInterfaceAction
  | SnapInterfaceControllerGetInterfaceAction
  | SnapInterfaceControllerGetInterfaceStateAction
  | SnapInterfaceControllerUpdateInterfaceAction
  | SnapInterfaceControllerDeleteInterfaceAction
  | SnapInterfaceControllerUpdateInterfaceStateAction
  | SnapInterfaceControllerResolveInterfaceAction
  | SnapInterfaceControllerSetInterfaceDisplayedAction;
