/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { CronjobController } from './CronjobController';

/**
 * Initialize the CronjobController.
 *
 * This starts the daily timer, clears out expired events
 * and reschedules any remaining events.
 */
export type CronjobControllerInitAction = {
  type: `CronjobController:init`;
  handler: CronjobController['init'];
};

/**
 * Schedule a non-recurring background event.
 *
 * @param event - The event to schedule.
 * @returns The ID of the scheduled event.
 */
export type CronjobControllerScheduleAction = {
  type: `CronjobController:schedule`;
  handler: CronjobController['schedule'];
};

/**
 * Cancel an event.
 *
 * @param origin - The origin making the cancel call.
 * @param id - The id of the event to cancel.
 * @throws If the event does not exist.
 */
export type CronjobControllerCancelAction = {
  type: `CronjobController:cancel`;
  handler: CronjobController['cancel'];
};

/**
 * Get a list of a Snap's background events.
 *
 * @param snapId - The id of the Snap to fetch background events for.
 * @returns An array of background events.
 */
export type CronjobControllerGetAction = {
  type: `CronjobController:get`;
  handler: CronjobController['get'];
};

/**
 * Union of all CronjobController action types.
 */
export type CronjobControllerMethodActions =
  | CronjobControllerInitAction
  | CronjobControllerScheduleAction
  | CronjobControllerCancelAction
  | CronjobControllerGetAction;
