/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { WebSocketService } from './WebSocketService';

/**
 * Open a WebSocket connection.
 *
 * @param snapId - The Snap ID.
 * @param url - The URL for the WebSocket connection.
 * @param protocols - An optional parameter for protocols.
 * @returns The identifier for the opened connection.
 * @throws If the connection fails.
 */
export type WebSocketServiceOpenAction = {
  type: `WebSocketService:open`;
  handler: WebSocketService['open'];
};

/**
 * Close a given WebSocket connection.
 *
 * @param snapId - The Snap ID.
 * @param id - The identifier for the WebSocket connection.
 */
export type WebSocketServiceCloseAction = {
  type: `WebSocketService:close`;
  handler: WebSocketService['close'];
};

/**
 * Send a message from a given Snap ID to a WebSocket connection.
 *
 * @param snapId - The Snap ID.
 * @param id - The identifier for the WebSocket connection.
 * @param data - The message to send.
 */
export type WebSocketServiceSendMessageAction = {
  type: `WebSocketService:sendMessage`;
  handler: WebSocketService['sendMessage'];
};

/**
 * Get a list of all open WebSocket connections for a Snap ID.
 *
 * @param snapId - The Snap ID.
 * @returns A list of WebSocket connections.
 */
export type WebSocketServiceGetAllAction = {
  type: `WebSocketService:getAll`;
  handler: WebSocketService['getAll'];
};

/**
 * Union of all WebSocketService action types.
 */
export type WebSocketServiceMethodActions =
  | WebSocketServiceOpenAction
  | WebSocketServiceCloseAction
  | WebSocketServiceSendMessageAction
  | WebSocketServiceGetAllAction;
