/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ExecutionService } from './ExecutionService';

export type ExecutionServiceTerminateSnapAction = {
  type: `ExecutionService:terminateSnap`;
  handler: ExecutionService['terminateSnap'];
};

export type ExecutionServiceTerminateAllSnapsAction = {
  type: `ExecutionService:terminateAllSnaps`;
  handler: ExecutionService['terminateAllSnaps'];
};

export type ExecutionServiceExecuteSnapAction = {
  type: `ExecutionService:executeSnap`;
  handler: ExecutionService['executeSnap'];
};

export type ExecutionServiceHandleRpcRequestAction = {
  type: `ExecutionService:handleRpcRequest`;
  handler: ExecutionService['handleRpcRequest'];
};

/**
 * Union of all ExecutionService action types.
 */
export type ExecutionServiceMethodActions =
  | ExecutionServiceTerminateSnapAction
  | ExecutionServiceTerminateAllSnapsAction
  | ExecutionServiceExecuteSnapAction
  | ExecutionServiceHandleRpcRequestAction;
