name: Validate pull request
on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  validate-pull-request-title:
    name: Validate title
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref , 'release/') }}
    steps:
      - name: Validate title
        # `amannn/action-semantic-pull-request@v5.4.0`
        uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
