// THIS IS A PROGRAMMATICALLY GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

type Version = string;
type PackageName = string;
type Private = boolean;
type Main = string;
type StringDj4X5WuP = string;
type StringXp6NyS6W = "https://registry.npmjs.org" | "https://registry.npmjs.org/";
type PublishConfig = {
  access?: StringDj4X5WuP;
  registry: StringXp6NyS6W;
  [k: string]: any;
}
type Repository = {
  type: StringDj4X5WuP;
  url: StringDj4X5WuP;
}
export type NpmSnapPackageJson = {
  version: Version;
  name: PackageName;
  private?: Private;
  main?: Main;
  publishConfig?: PublishConfig;
  repository?: Repository;
  [k: string]: any;
}
